name: Foxy

on:
  push:
    branches: [main, ci/*, chore/*, feat/*, fix/*]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    container: ros:foxy-ros-base
    env:
      PIP_BREAK_SYSTEM_PACKAGES: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          apt-get update -y
          apt-get install -y python3-pip python3-colcon-common-extensions git
          . /opt/ros/foxy/setup.sh
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y --rosdistro foxy
          pip3 install src/agent/symphony-sdk-python/

      - name: Build
        run: |
          . /opt/ros/foxy/setup.sh
          colcon build --packages-select muto_msgs muto_core muto_agent muto_composer eclipse_muto

      - name: Test
        run: |
          . /opt/ros/foxy/setup.sh
          . install/setup.sh
          colcon test --packages-select muto_agent muto_composer muto_core muto_msgs --event-handlers console_direct+
          colcon test-result --verbose
