name: Colcon Build and Test

on:
  push:
    branches: [main, ci/*, chore/*, feat/*, fix/*]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        ros_distro: [humble, jazzy]
        include:
          - ros_distro: humble
            os: ubuntu-22.04
          - ros_distro: jazzy
            os: ubuntu-24.04
    runs-on: ${{ matrix.os }}
    container: osrf/ros:${{ matrix.ros_distro }}-desktop
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          apt-get update -y
          apt-get install -y python3-pip
          . /opt/ros/${{ matrix.ros_distro }}/setup.sh
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y --rosdistro ${{ matrix.ros_distro }}
          pip3 install src/agent/symphony-sdk-python/

      - name: Build
        run: |
          . /opt/ros/${{ matrix.ros_distro }}/setup.sh
          colcon build --packages-select muto_msgs muto_core muto_agent muto_composer eclipse_muto

      - name: Test
        run: |
          . /opt/ros/${{ matrix.ros_distro }}/setup.sh
          . install/setup.sh
          colcon test --packages-select muto_agent muto_composer muto_core muto_msgs --event-handlers console_direct+
          colcon test-result --verbose
